### ISSUE TITLE
[Feature Request] Output preliminary results in progress indicator

### ISSUE THREAD

**Issue by corneliusroemer** [treysis/playstore-country-check#1]
Great work, runs smoothly, straightaway without any issues.

The only thing that made me worried while the program was running was that I didn't get any preliminary results. Would be nice if it at least displayed in the progress indicator for how many countries the app was found in the play store - so that one knows everything is working well.

Also, maybe add a requirements.txt in case any extra requirements appear for easy install using 
`pip install -r requirements.txt`

**Comment by treysis** [comment]
I actually had the "live reporting" implemented before the progress indicator. But it didn't look nice enough :) Reporting the number of supported countries seems good. Though I also see good reasons for even more direct feedback. Well, design choices are difficult 😐

**Comment by treysis** [comment]
Changed with https://github.com/treysis/playstore-country-check/commit/447c04b06a86cb3e5773e65b6fb9c4f9e86e98c3

**Comment by treysis** [comment]
Better?

**Comment by corneliusroemer** [comment]
Looks good, but now put the country lists into a separate file :')

**Comment by treysis** [comment]
That seems like a good idea. Also makes it easier to create custom lists.

But...you know the rulez! New issue, new thread!! Otherwise: violation of my secret community guidelines!!! 😉
